# Generated by Django 4.1.1 on 2022-12-18 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('fechainscripcion', models.DateField()),
                ('institucion', models.CharField(max_length=50)),
                ('horainscripcion', models.TimeField()),
                ('estado', models.CharField(choices=[['RESERVADO', 'RESERVADO'], ['COMPLETADO', 'COMPLETADO'], ['ANULADO', 'ANULADO'], ['NO ASISTEN', 'NO ASISTEN']], max_length=50)),
                ('observacion', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
